# Generated by Django 4.2.7 on 2025-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_1h',
            field=models.BooleanField(default=False, help_text='Whether 1-hour reminder has been sent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_24h',
            field=models.BooleanField(default=False, help_text='Whether 24-hour reminder has been sent'),
        ),
    ]
